name: GitHub Issue Sync

on:
  issues:
    types:
      - opened
  workflow_dispatch:
    inputs:
      excludeClosed:
        description: 'Exclude closed issues in the sync.'
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install CLI App
        run: cd cli && cargo install --path .

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run CLI App
        id: expected
        run: echo "results=$(para-onboarding 2000 5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw -g './test/para-2000-genesis-state' -v './test/para-2000-wasm')" >> $GITHUB_OUTPUT
        env:
          SEED: ${{ secrets.SEED }}
          FAUCET_ADDRESS: ${{ secrets.FAUCET_ADDRESS }}
          ROCOCO_URI: ${{ secrets.ROCOCO_URI }}